# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rxVvJudYewJAsJi8jPbLM-p1wK0jtmsJ
"""

from google.colab import drive
drive.mount('/content/drive')

# %cd drive/My\ Drive

!git clone https://github.com/cchen156/Learning-to-See-in-the-Dark.git

# %cd Learning-to-See-in-the-Dark/

!python train_Fuji.py

!python train_Sony.py

!python download_dataset.py

!pip install Tensorflow Scipy Numpy Rawpy

!python test_Sony.py

!python test_Fuji.py

!ls /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/

!mkdir tmpfs

!ls

!df -h /content/drive/My\ Drive

!export TMPDIR=tmpfs

!git clone https://github.com/cchen156/Learning-to-See-in-the-Dark.git

!pip install Tensorflow Scipy Numpy Rawpy

!pip install Tensorflow Scipy Numpy Rawpy
!ls Learning-to-See-in-the-Dark/
# %cd Learning-to-See-in-the-Dark/
!python download_dataset.py