# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rxVvJudYewJAsJi8jPbLM-p1wK0jtmsJ
"""

from google.colab import drive
drive.mount('/content/drive')

# %cd drive/My\ Drive

# %cd Learning-to-See-in-the-Dark/

import numpy
intinfo = numpy.iinfo(int)
numpy.random.randint(-1, intinfo.max)
numpy.random.randint(intinfo.min, intinfo.max)

!pip install Tensorflow Scipy Numpy Rawpy

!python train_Sony.py

!python download_models.py

!python test_Fuji.py

!python test_Sony.py

!ls result_Sony/final

import cv2 as cv
import matplotlib.pyplot as plt
import os.path

def clearLabel(_ax):
  _ax.tick_params(labelbottom="off",bottom="off")
  _ax.tick_params(labelleft="off",left="off")
  _ax.set_xticklabels([]) 
  _ax.axis('off')
  return _ax

def readImage(_filename):
  if os.path.exists(_filename):
    img = cv.imread(_filename)
    return img

img1 = readImage('result_Sony/final/10003_00_100_gt.png')
img2 = readImage('result_Sony/final/10003_00_100_out.png')
img3 = readImage('result_Sony/final/10003_00_100_scale.png')

fig = plt.figure()

ax1 = fig.add_subplot(1, 3, 1)
clearLabel(ax1)
show_img1 = cv.cvtColor(img1, cv.COLOR_BGR2RGB) 
plt.imshow(show_img1)

ax2 = fig.add_subplot(1, 3, 2)
clearLabel(ax2)
show_img2 = cv.cvtColor(img2, cv.COLOR_BGR2RGB) 
plt.imshow(show_img2)

ax3 = fig.add_subplot(1, 3, 3)
clearLabel(ax3)
show_img3 = cv.cvtColor(img3, cv.COLOR_BGR2RGB) 
plt.imshow(show_img3)

plt.show()

!python train_Fuji.py

!python download_dataset.py

!ls /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/

!mkdir tmpfs

!git clone https://github.com/cchen156/Learning-to-See-in-the-Dark.git

!ls

!df -h /content/drive/My\ Drive

!export TMPDIR=tmpfs

!git clone https://github.com/cchen156/Learning-to-See-in-the-Dark.git

!pip install Tensorflow Scipy Numpy Rawpy

!pip install Tensorflow Scipy Numpy Rawpy
!ls Learning-to-See-in-the-Dark/
# %cd Learning-to-See-in-the-Dark/
!python download_dataset.py